# Generated by Django 5.0.1 on 2024-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_product_related_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_product',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.product'),
        ),
    ]
